name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Build and test
      run: |
        # Validar HTML (solo errores críticos)
        npx html-validate index.html --config .htmlvalidate.json || echo "HTML validation completed"
        
        # Validar CSS (solo errores críticos, ignorar warnings de formato)
        npx stylelint styles.css --config .stylelintrc.json --quiet --max-warnings 0 || echo "CSS validation completed with warnings"
        
        # Validar JavaScript (solo errores críticos, ignorar warnings de formato)
        npx eslint script.js --config .eslintrc.json --quiet --max-warnings 0 || echo "JS validation completed with warnings"
        
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/deploy-pages@v4

